server:
  forward-headers-strategy: NATIVE

ncp:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME:pdf-bucket01}
        endpoint: ${S3_ENDPOINT:https://s3.ap-northeast-2.amazonaws.com}
        region: ${AWS_REGION:ap-northeast-2}

# SQS 큐 설정
queue:
  json-event-url: ${SQS_QUEUE_URL}
  # 추가: 큐 이름만 별도로 설정
  json-event-name: ${SQS_QUEUE_NAME:JsonEvent}

# Flask 서버 주소
kanji:
  api:
    base-url: ${KANJI_API_BASE_URL}

# Spring Cloud AWS SQS 설정
spring:
  cloud:
    aws:
      sqs:
        enabled: true
      region:
        static: ${AWS_REGION:ap-northeast-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}