name: Deploy to EC2

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASTION_IP: ${{ secrets.EC2_HOST }}
      BACKEND_IP: ${{ secrets.BACKEND_HOST }}
    steps:
      - name: Setup SSH Keys and Config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/bastion_key
          chmod 600 ~/.ssh/bastion_key
          
          # SSH config 파일 생성
          cat > ~/.ssh/config << EOF
          Host bastion
            HostName ${{ env.BASTION_IP }}
            User ec2-user
            IdentityFile ~/.ssh/bastion_key
            StrictHostKeyChecking no
          
          Host backend
            HostName ${{ env.BACKEND_IP }}
            User ubuntu
            IdentityFile ~/.ssh/bastion_key
            ProxyJump bastion
            StrictHostKeyChecking no
          EOF

      - name: Execute Deployment Commands on Backend
        run: |
          ssh backend "
          docker pull hwangjungseok/lingua-backend:latest;
          docker stop lingua-backend || true;
          docker rm lingua-backend || true;
          IMAGE_ID=\$(docker images -q hwangjungseok/lingua-backend:latest | head -n 1);
          docker image prune -f;
          if [ ! -z \"\$IMAGE_ID\" ]; then
            docker images -q | grep -v \$IMAGE_ID | xargs -r docker rmi;
          fi;
          docker run -d -p 8080:8080 \
            --env-file /home/ubuntu/.env \
            -e AWS_SECRET_KEY='${{ secrets.AWS_SECRET_KEY }}' \
            -e AWS_ACCESS_KEY='${{ secrets.AWS_ACCESS_KEY }}' \
            -e S3_BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' \
            -e S3_ENDPOINT='${{ secrets.S3_ENDPOINT }}' \
            -e AWS_REGION='${{ secrets.AWS_REGION }}' \
            -e SQS_QUEUE_URL='${{ secrets.SQS_QUEUE_URL }}' \
            -e SQS_QUEUE_NAME='${{ secrets.SQS_QUEUE_NAME }}' \
            -e KANJI_API_BASE_URL='${{ secrets.KANJI_API_BASE_URL }}' \
            -e MODEL_NAME='${{ secrets.MODEL_NAME }}' \
            -e GEMINI_API_KEY='${{ secrets.GEMINI_API_KEY }}' \
            -e NODE_ENV='EC2' \
            -e PINPOINT_AGENT_ID='${{ secrets.PINPOINT_AGENT_ID }}' \
            -e PINPOINT_APPLICATION_NAME='${{ secrets.PINPOINT_APPLICATION_NAME }}' \
            -e PINPOINT_COLLECTOR_IP='${{ secrets.PINPOINT_COLLECTOR_IP }}' \
            -e JAVA_TOOL_OPTIONS='-javaagent:/pinpoint-agent/pinpoint-bootstrap-2.5.4.jar -Dpinpoint.agentId=${{ secrets.PINPOINT_AGENT_ID }} -Dpinpoint.applicationName=${{ secrets.PINPOINT_APPLICATION_NAME }} -Dpinpoint.profiler.transport.grpc.collector.ip=${{ secrets.PINPOINT_COLLECTOR_IP }} -Dpinpoint.profiler.sampling.counting.sampling-rate=1' \
            -v \$(pwd)/pinpoint-agent-2.5.4:/pinpoint-agent \
            --restart always \
            --name lingua-backend \
            hwangjungseok/lingua-backend:latest"